name: Archingstudio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37376
title: Associazione Professionale Architetti e Ingegneri
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6bc52f'
    - '#333333'
    - '#000000'
    - '#249d3d'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
