name: Archingstudio
favicon: null
layout_spectrum: 0.45065330527722836
typography_spectrum: 0.8445454742759466
title: Progetti di architettura e ingegneria
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#98cd37'
    - '#000000'
    - '#2a2a2a'
    - '#868686'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
