name: Archingstudio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22685
title: Progetti di architettura e ingegneria
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1cfc5'
    - '#8c9fc0'
    - '#070b0a'
    - '#3e706d'
    - '#454346'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
